include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'test/.test_coverage.dart'
    - 'test/*'
    - 'bin/cache/**'
    - 'lib/generated_plugin_registrant.dart'
    # - lib/product/init/language/
    # - lib/product/init/generation/

linter:
  rules:
    public_member_api_docs: false # if you do not develop package or plugin leave this false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
